kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim  # Define a 'Persistent Voulume Claim'(PVC) for Postgress Storage, dynamically provisioned by cluster
apiVersion: v1
metadata:
  name: postgres-pv-claim  # name of PVC essential for identifying the storage data
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 5Gi #This will tell kubernetes about the amount of space we are trying to claim.